# Generated by Django 4.2.17 on 2025-01-06 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ElegantDecor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendor_id", models.CharField(max_length=100)),
                ("member_id", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=255)),
                ("category_id", models.CharField(max_length=100)),
                ("vendor_currency", models.CharField(max_length=10)),
                ("membership_id", models.CharField(max_length=100)),
                ("new_slug", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("information", models.TextField()),
                ("vendor_rating", models.CharField(max_length=10)),
                ("reviews_count", models.CharField(max_length=100)),
                ("vendor_price", models.CharField(max_length=100)),
                ("starting_price_new", models.CharField(max_length=100)),
                ("vendor_price_subtext", models.CharField(max_length=100)),
                ("vendor_verification_status", models.BooleanField()),
                ("vaccination_status", models.IntegerField()),
                ("secret_deal_available", models.BooleanField()),
                ("profile_pic_url", models.URLField()),
                ("is_mynt", models.BooleanField()),
                ("category_price_suffix_text", models.CharField(max_length=255)),
                ("starting_price", models.CharField(max_length=100)),
                ("show_badge_icon", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="CoverImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField()),
                (
                    "elegant_decor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="decorators.elegantdecor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CityPolygon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pinned_to_bottom", models.IntegerField()),
                ("review_score", models.FloatField()),
                ("freshness_score", models.FloatField()),
                ("image_score", models.FloatField()),
                ("lrr_score", models.FloatField()),
                ("membership_id", models.IntegerField()),
                ("score", models.FloatField()),
                ("city_slug", models.CharField(max_length=100)),
                ("city_name", models.CharField(max_length=100)),
                ("is_base_city", models.CharField(max_length=10)),
                (
                    "elegant_decor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="decorators.elegantdecor",
                    ),
                ),
            ],
        ),
    ]
