# Generated by Django 4.2.17 on 2025-01-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decorators", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citypolygon",
            name="pinned_to_bottom",
            field=models.IntegerField(null=True),
        ),
    ]
