# Generated by Django 4.2.17 on 2025-01-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decorators", "0002_alter_citypolygon_pinned_to_bottom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elegantdecor",
            name="information",
            field=models.TextField(null=True),
        ),
    ]
