# Generated by Django 4.2.17 on 2025-01-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decorators", "0003_alter_elegantdecor_information"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citypolygon",
            name="city_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="citypolygon",
            name="city_slug",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="citypolygon",
            name="freshness_score",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="citypolygon",
            name="image_score",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="citypolygon",
            name="is_base_city",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="citypolygon",
            name="lrr_score",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="citypolygon",
            name="membership_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="citypolygon",
            name="review_score",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="citypolygon", name="score", field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="elegantdecor",
            name="category_id",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="elegantdecor",
            name="category_price_suffix_text",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="elegantdecor",
            name="city",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="elegantdecor",
            name="is_mynt",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="elegantdecor",
            name="membership_id",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="elegantdecor",
            name="new_slug",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="elegantdecor",
            name="profile_pic_url",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="elegantdecor",
            name="reviews_count",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="elegantdecor",
            name="secret_deal_available",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="elegantdecor",
            name="show_badge_icon",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="elegantdecor",
            name="starting_price",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="elegantdecor",
            name="starting_price_new",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="elegantdecor",
            name="vaccination_status",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="elegantdecor",
            name="vendor_currency",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="elegantdecor",
            name="vendor_price",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="elegantdecor",
            name="vendor_price_subtext",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="elegantdecor",
            name="vendor_rating",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="elegantdecor",
            name="vendor_verification_status",
            field=models.BooleanField(null=True),
        ),
    ]
