# Generated by Django 4.2.17 on 2025-01-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decorators", "0004_alter_citypolygon_city_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citypolygon",
            name="review_score",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
