# Generated by Django 4.2.17 on 2025-01-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decorators", "0005_alter_citypolygon_review_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citypolygon",
            name="freshness_score",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="citypolygon",
            name="image_score",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="citypolygon",
            name="lrr_score",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="citypolygon",
            name="score",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
