# Generated by Django 4.2.17 on 2025-01-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decorators", "0006_alter_citypolygon_freshness_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citypolygon",
            name="membership_id",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
