# Generated by Django 4.2.17 on 2025-01-06 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendor_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("membership_id", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("locality", models.CharField(max_length=255)),
                ("information", models.TextField()),
                (
                    "vendor_rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("reviews_count", models.IntegerField(default=0)),
                ("vendor_price", models.CharField(max_length=255)),
                ("vendor_price_subtext", models.CharField(max_length=255)),
                ("vendor_verification_status", models.BooleanField(default=False)),
                ("vaccination_status", models.BooleanField(default=False)),
                ("secret_deal_available", models.BooleanField(default=False)),
                ("profile_pic_url", models.URLField()),
                ("is_mynt", models.BooleanField(default=False)),
                ("starting_price", models.CharField(max_length=255)),
                ("show_badge_icon", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="VenueType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("venue_type", models.CharField(max_length=255)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="venue_types",
                        to="venue.vendor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VenuePricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destination_price_prefix", models.CharField(max_length=255)),
                ("destination_price", models.CharField(max_length=255)),
                ("destination_price_unit", models.CharField(max_length=255)),
                ("vendor_currency", models.CharField(max_length=255)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing",
                        to="venue.vendor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VenueImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField()),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="venue_images",
                        to="venue.vendor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VenueCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=255)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="venue.vendor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tooltip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tooltips",
                        to="venue.vendor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GuestCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_value", models.IntegerField()),
                ("max_value", models.IntegerField()),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_counts",
                        to="venue.vendor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("answer", models.TextField()),
                ("faq_order", models.IntegerField()),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faqs",
                        to="venue.vendor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CityPolygon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pinned_to_bottom", models.IntegerField(default=0)),
                (
                    "review_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                (
                    "freshness_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                (
                    "image_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                (
                    "lrr_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                (
                    "score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("city_slug", models.CharField(max_length=255)),
                ("city_name", models.CharField(max_length=255)),
                ("is_base_city", models.IntegerField(default=0)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="city_polygon",
                        to="venue.vendor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BadgeIcon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("web_icon", models.URLField()),
                ("android_hdmi", models.URLField()),
                ("android_mdpi", models.URLField()),
                ("ios_1x", models.URLField()),
                ("ios_2x", models.URLField()),
                ("is_new_badge", models.BooleanField(default=False)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badge_icons",
                        to="venue.vendor",
                    ),
                ),
            ],
        ),
    ]
