# Generated by Django 4.2.17 on 2025-01-06 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("venue", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="citypolygon", name="image_score",),
        migrations.RemoveField(model_name="citypolygon", name="lrr_score",),
        migrations.AlterField(
            model_name="citypolygon",
            name="freshness_score",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="citypolygon",
            name="pinned_to_bottom",
            field=models.CharField(default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="citypolygon",
            name="review_score",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="citypolygon",
            name="vendor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="city_polygon",
                to="venue.vendor",
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="city",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="vendor", name="information", field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="is_mynt",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="locality",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="profile_pic_url",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="reviews_count",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="secret_deal_available",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="show_badge_icon",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="starting_price",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="vaccination_status",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="vendor_price",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="vendor_price_subtext",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="vendor_rating",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="vendor_verification_status",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="venuecategory",
            name="category_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="venueimage", name="image_url", field=models.URLField(null=True),
        ),
    ]
