name: Fullstack CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]
        node-version: [20.x]

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up Python
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    # Step 3: Install backend dependencies
    - name: Install backend dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    # Step 4: Run Django tests
    - name: Run backend tests
      working-directory: backend
      run: |
        python manage.py test

    # Step 5: Set up Node.js
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    # Step 6: Install frontend dependencies
    - name: Install frontend dependencies
      working-directory: frontend
      run: npm install

    # Step 7: Run React build
    - name: Build frontend
      working-directory: frontend
      run: npm run build

    # Step 8: Run frontend tests
    - name: Run frontend tests
      working-directory: frontend
      run: npm test

